// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUIqYIgOjI2TVd096SPe9OcT7FGQpWRc',
    appId: '1:934898325100:web:948d8789a705b2b974ea49',
    messagingSenderId: '934898325100',
    projectId: 'acessibus-df8c9',
    authDomain: 'acessibus-df8c9.firebaseapp.com',
    storageBucket: 'acessibus-df8c9.firebasestorage.app',
    measurementId: 'G-L00PTXJX9B',
    databaseURL: 'https://acessibus-df8c9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJUIqYIgOjI2TVd096SPe9OcT7FGQpWRc',
    appId: '1:934898325100:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '934898325100',
    projectId: 'acessibus-df8c9',
    storageBucket: 'acessibus-df8c9.firebasestorage.app',
    databaseURL: 'https://acessibus-df8c9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJUIqYIgOjI2TVd096SPe9OcT7FGQpWRc',
    appId: '1:934898325100:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '934898325100',
    projectId: 'acessibus-df8c9',
    storageBucket: 'acessibus-df8c9.firebasestorage.app',
    iosBundleId: 'com.example.acessibus',
    databaseURL: 'https://acessibus-df8c9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJUIqYIgOjI2TVd096SPe9OcT7FGQpWRc',
    appId: '1:934898325100:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '934898325100',
    projectId: 'acessibus-df8c9',
    storageBucket: 'acessibus-df8c9.firebasestorage.app',
    iosBundleId: 'com.example.acessibus',
    databaseURL: 'https://acessibus-df8c9-default-rtdb.firebaseio.com',
  );
}


